### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [Annarau21/prj-rev-bwfs-dasmoto#5]
Stellar job on this project! I really liked your use of divs to structure your code, and how clean and easy to read your code was. In terms of improvement, I recommend removing the font-weight: bold on your h2s, using spans in your HTML, migrating your span stylings to the CSS, and reducing duplicate stylings in your CSS. 

If you’re in the mood for a challenge...I would look into adding more items to each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the hard work! ^_^

**Comment by Annarau21** [comment]
Thank you! I will start to adjust my code to not have duplicate mentions.
